/*
Copyright 2026 The KubeVela Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package analysis

import (
	"fmt"
	"os"
	"path/filepath"
	"testing"

	"cuelang.org/go/cue/format"
	"github.com/stretchr/testify/require"

	"github.com/oam-dev/kubevela/pkg/definition/kubeschema"
)

// addon_application.cue is generated from the Application CRD, so an addon's
// output is checked against the Application this KubeVela accepts. Run
// `go test ./pkg/definition/analysis -run TestAddonApplicationMatchesTheCRD -update`
// after the CRD changes.
func TestAddonApplicationMatchesTheCRD(t *testing.T) {
	got, err := generateAddonApplication(filepath.Join("..", "..", "..", "charts", "vela-core", "crds", "core.oam.dev_applications.yaml"))
	require.NoError(t, err)
	if *update {
		require.NoError(t, os.WriteFile("addon_application.cue", got, 0o600))
	}
	want, err := os.ReadFile("addon_application.cue")
	require.NoError(t, err)
	require.Equal(t, string(got), string(want), "addon_application.cue is stale: rerun this test with -update")
}

func generateAddonApplication(crdFile string) ([]byte, error) {
	data, err := os.ReadFile(crdFile)
	if err != nil {
		return nil, err
	}
	kinds := kubeschema.New()
	if err := kinds.AddCRD(data); err != nil {
		return nil, err
	}
	gvk := kubeschema.ParseGVK("core.oam.dev/v1beta1", "Application")
	src, ok := kinds.CUE(gvk)
	if !ok {
		return nil, fmt.Errorf("%s has no core.oam.dev/v1beta1 Application", crdFile)
	}
	out := "// Code generated by TestAddonApplicationMatchesTheCRD from charts/vela-core/crds. DO NOT EDIT.\n\n" +
		"// #addonApplication is the Application an addon's template.cue outputs.\n" +
		"#addonApplication: " + kubeschema.Root(gvk) + "\n" + src
	return format.Source([]byte(out))
}
