// Code generated by TestHeaderAttributesMatchTheCRDs from charts/vela-core/crds. DO NOT EDIT.

// #attributes is what a definition header's attributes may hold, by type:
// the Definition CRD's spec, less the schematic, which is the template.
#attributes: {
	"component": {
		// Abstract marks this definition as one that may only be extended, never
		// named directly by an Application. A base that applies a platform's rules
		// is not something to use as-is, and saying so here is what makes the
		// definitions built on it the only way through.
		// It is not inherited: a definition that extends an abstract one is usable
		// unless it marks itself abstract too.
		"abstract"?: bool
		// ChildResourceKinds are the list of GVK of the child resources this workload generates
		"childResourceKinds"?: [...{
			// APIVersion of the child resource
			"apiVersion"!: string
			// Kind of the child resource
			"kind"!: string
			// Selector to select the child resources that the workload wants to expose to traits
			"selector"?: {[string]: string}
		}]
		// Extends names a ComponentDefinition this one builds on. The parent renders
		// with the parameters this definition's template passes it in its `$super`
		// block, and its output, outputs and parameter schema are inherited unless
		// the template says otherwise with `$inherit`.
		// A DefinitionRevision may be named to pin the parent, as in
		// "webservice@v3"; an unqualified name tracks whatever is current. The
		// ancestors a render resolved are recorded in the ApplicationRevision, so an
		// application keeps rendering the same way after a parent changes.
		"extends"?: string
		// Extension is used for extension needs by OAM platform builders
		"extension"?: {...}
		// PodSpecPath indicates where/if this workload has K8s podSpec field
		// if one workload has podSpec, trait can do lot's of assumption such as port, env, volume fields.
		"podSpecPath"?: string
		// Restrictions limits where this definition may be used. Absent or empty means
		// usable anywhere. A non-empty block overrides the
		// definition.oam.dev/restrict-namespaces annotation.
		"restrictions"?: {
			// NamespaceSelector selects those namespaces by label instead, for membership
			// that is not a naming convention. An empty selector matches every namespace;
			// leave the field unset to express no opinion.
			// Anyone who can label a namespace can bring it into scope, which a name glob
			// does not allow without the right to create namespaces.
			"namespaceSelector"?: {
				// matchExpressions is a list of label selector requirements. The requirements are ANDed.
				"matchExpressions"?: [...{
					// key is the label key that the selector applies to.
					"key"!: string
					// operator represents a key's relationship to a set of values.
					// Valid operators are In, NotIn, Exists and DoesNotExist.
					"operator"!: string
					// values is an array of string values. If the operator is In or NotIn,
					// the values array must be non-empty. If the operator is Exists or DoesNotExist,
					// the values array must be empty. This array is replaced during a strategic
					// merge patch.
					"values"?: [...string]
				}]
				// matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels
				// map is equivalent to an element of matchExpressions, whose key field is "key", the
				// operator is "In", and the values array contains only "value". The requirements are ANDed.
				"matchLabels"?: {[string]: string}
			}
			// Namespaces are the namespaces whose Applications may use this definition, as
			// names or globs ("tenant-*", matched with path.Match).
			"namespaces"?: [...string]
			// Quota limits how many uses of this definition one namespace may contain. The
			// first entry matching the namespace applies, so an entry with no matcher reads
			// as the default and belongs last. Absent or empty means unlimited.
			// Only ComponentDefinition and TraitDefinition are counted, and a quota on any
			// other kind is rejected when the definition is written. A namespace
			// accumulates components and the traits on them; a policy, workflow step or
			// source is part of how one Application is assembled.
			// The system namespace is never subject to a quota: addons install their own
			// Applications there using these definitions.
			"quota"?: [...{
				// Limit is the most uses of this definition the namespace may contain. Omit to
				// warn without ever refusing; zero forbids the type outright.
				"limit"?: int
				// NamespaceSelector selects those namespaces by label instead. It and
				// Namespaces are alternatives, so either one matching selects the entry.
				"namespaceSelector"?: {
					// matchExpressions is a list of label selector requirements. The requirements are ANDed.
					"matchExpressions"?: [...{
						// key is the label key that the selector applies to.
						"key"!: string
						// operator represents a key's relationship to a set of values.
						// Valid operators are In, NotIn, Exists and DoesNotExist.
						"operator"!: string
						// values is an array of string values. If the operator is In or NotIn,
						// the values array must be non-empty. If the operator is Exists or DoesNotExist,
						// the values array must be empty. This array is replaced during a strategic
						// merge patch.
						"values"?: [...string]
					}]
					// matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels
					// map is equivalent to an element of matchExpressions, whose key field is "key", the
					// operator is "In", and the values array contains only "value". The requirements are ANDed.
					"matchLabels"?: {[string]: string}
				}
				// Namespaces are the namespaces this entry applies to, as names or globs
				// ("tenant-*", matched with path.Match). Leave both matchers unset to make the
				// entry the default.
				"namespaces"?: [...string]
				// Warn is the count at or above which the Application is admitted with a
				// warning.
				"warn"?: int
			}]
		}
		// RevisionLabel indicates which label for underlying resources(e.g. pods) of this workload
		// can be used by trait to create resource selectors(e.g. label selector for pods).
		"revisionLabel"?: string
		// Status defines the custom health policy and status message for workload
		"status"?: {
			// CustomStatus defines the custom status message that could display to user
			"customStatus"?: string
			// Details stores a string representation of a CUE status map to be evaluated at runtime for display
			"details"?: string
			// HealthPolicy defines the health check policy for the abstraction
			"healthPolicy"?: string
		}
		"version"?: string
		// Workload is a workload type descriptor
		"workload"!: {
			// Definition mutually exclusive to workload.type, a embedded WorkloadDefinition
			"definition"?: {
				"apiVersion"!: string
				"kind"!:       string
			}
			// Type ref to a WorkloadDefinition via name
			"type"?: string
		}
	}
	"policy": {
		// Reference to the CustomResourceDefinition that defines this trait kind.
		"definitionRef"?: {
			// Name of the referenced CustomResourceDefinition.
			"name"!: string
			// Version indicate which version should be used if CRD has multiple versions
			// by default it will use the first one if not specified
			"version"?: string
		}
		// Global indicates this policy should automatically apply to all Applications
		// in this namespace (or all namespaces if in vela-system).
		// Global policies cannot be explicitly referenced in Application specs.
		// Requires EnableGlobalPolicies feature gate for discovery and
		// EnableApplicationScopedPolicies feature gate for execution.
		"global"?: bool
		// ManageHealthCheck means the policy will handle health checking and skip application controller
		// built-in health checking.
		"manageHealthCheck"?: bool
		// Priority defines the order in which global policies are applied.
		// Lower values run first (e.g. 0 runs before 100), following the same
		// convention as Kubernetes admission webhooks. Policies with the same
		// priority are applied in alphabetical order by name.
		// If not specified, defaults to 0.
		"priority"?: int
		// Restrictions limits where this definition may be used. Absent or empty means
		// usable anywhere. A non-empty block overrides the
		// definition.oam.dev/restrict-namespaces annotation.
		"restrictions"?: {
			// NamespaceSelector selects those namespaces by label instead, for membership
			// that is not a naming convention. An empty selector matches every namespace;
			// leave the field unset to express no opinion.
			// Anyone who can label a namespace can bring it into scope, which a name glob
			// does not allow without the right to create namespaces.
			"namespaceSelector"?: {
				// matchExpressions is a list of label selector requirements. The requirements are ANDed.
				"matchExpressions"?: [...{
					// key is the label key that the selector applies to.
					"key"!: string
					// operator represents a key's relationship to a set of values.
					// Valid operators are In, NotIn, Exists and DoesNotExist.
					"operator"!: string
					// values is an array of string values. If the operator is In or NotIn,
					// the values array must be non-empty. If the operator is Exists or DoesNotExist,
					// the values array must be empty. This array is replaced during a strategic
					// merge patch.
					"values"?: [...string]
				}]
				// matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels
				// map is equivalent to an element of matchExpressions, whose key field is "key", the
				// operator is "In", and the values array contains only "value". The requirements are ANDed.
				"matchLabels"?: {[string]: string}
			}
			// Namespaces are the namespaces whose Applications may use this definition, as
			// names or globs ("tenant-*", matched with path.Match).
			"namespaces"?: [...string]
			// Quota limits how many uses of this definition one namespace may contain. The
			// first entry matching the namespace applies, so an entry with no matcher reads
			// as the default and belongs last. Absent or empty means unlimited.
			// Only ComponentDefinition and TraitDefinition are counted, and a quota on any
			// other kind is rejected when the definition is written. A namespace
			// accumulates components and the traits on them; a policy, workflow step or
			// source is part of how one Application is assembled.
			// The system namespace is never subject to a quota: addons install their own
			// Applications there using these definitions.
			"quota"?: [...{
				// Limit is the most uses of this definition the namespace may contain. Omit to
				// warn without ever refusing; zero forbids the type outright.
				"limit"?: int
				// NamespaceSelector selects those namespaces by label instead. It and
				// Namespaces are alternatives, so either one matching selects the entry.
				"namespaceSelector"?: {
					// matchExpressions is a list of label selector requirements. The requirements are ANDed.
					"matchExpressions"?: [...{
						// key is the label key that the selector applies to.
						"key"!: string
						// operator represents a key's relationship to a set of values.
						// Valid operators are In, NotIn, Exists and DoesNotExist.
						"operator"!: string
						// values is an array of string values. If the operator is In or NotIn,
						// the values array must be non-empty. If the operator is Exists or DoesNotExist,
						// the values array must be empty. This array is replaced during a strategic
						// merge patch.
						"values"?: [...string]
					}]
					// matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels
					// map is equivalent to an element of matchExpressions, whose key field is "key", the
					// operator is "In", and the values array contains only "value". The requirements are ANDed.
					"matchLabels"?: {[string]: string}
				}
				// Namespaces are the namespaces this entry applies to, as names or globs
				// ("tenant-*", matched with path.Match). Leave both matchers unset to make the
				// entry the default.
				"namespaces"?: [...string]
				// Warn is the count at or above which the Application is admitted with a
				// warning.
				"warn"?: int
			}]
		}
		// Scope defines the scope at which this policy operates.
		// - DefaultScope (empty/omitted): Standard output-based or builtin policies (topology, override, etc.)
		//   These can generate Kubernetes resources from CUE templates with an 'output' field or apply Go-logic in the controller
		// - ApplicationScope: Transform-based policies that modify the Application CR before parsing.
		//   Requires EnableApplicationScopedPolicies feature gate.
		"scope"?:   string
		"version"?: string
	}
	"source": {
		// Restrictions limits where this definition may be used. Absent or empty means
		// usable anywhere. A non-empty block overrides the
		// definition.oam.dev/restrict-namespaces annotation.
		"restrictions"?: {
			// NamespaceSelector selects those namespaces by label instead, for membership
			// that is not a naming convention. An empty selector matches every namespace;
			// leave the field unset to express no opinion.
			// Anyone who can label a namespace can bring it into scope, which a name glob
			// does not allow without the right to create namespaces.
			"namespaceSelector"?: {
				// matchExpressions is a list of label selector requirements. The requirements are ANDed.
				"matchExpressions"?: [...{
					// key is the label key that the selector applies to.
					"key"!: string
					// operator represents a key's relationship to a set of values.
					// Valid operators are In, NotIn, Exists and DoesNotExist.
					"operator"!: string
					// values is an array of string values. If the operator is In or NotIn,
					// the values array must be non-empty. If the operator is Exists or DoesNotExist,
					// the values array must be empty. This array is replaced during a strategic
					// merge patch.
					"values"?: [...string]
				}]
				// matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels
				// map is equivalent to an element of matchExpressions, whose key field is "key", the
				// operator is "In", and the values array contains only "value". The requirements are ANDed.
				"matchLabels"?: {[string]: string}
			}
			// Namespaces are the namespaces whose Applications may use this definition, as
			// names or globs ("tenant-*", matched with path.Match).
			"namespaces"?: [...string]
			// Quota limits how many uses of this definition one namespace may contain. The
			// first entry matching the namespace applies, so an entry with no matcher reads
			// as the default and belongs last. Absent or empty means unlimited.
			// Only ComponentDefinition and TraitDefinition are counted, and a quota on any
			// other kind is rejected when the definition is written. A namespace
			// accumulates components and the traits on them; a policy, workflow step or
			// source is part of how one Application is assembled.
			// The system namespace is never subject to a quota: addons install their own
			// Applications there using these definitions.
			"quota"?: [...{
				// Limit is the most uses of this definition the namespace may contain. Omit to
				// warn without ever refusing; zero forbids the type outright.
				"limit"?: int
				// NamespaceSelector selects those namespaces by label instead. It and
				// Namespaces are alternatives, so either one matching selects the entry.
				"namespaceSelector"?: {
					// matchExpressions is a list of label selector requirements. The requirements are ANDed.
					"matchExpressions"?: [...{
						// key is the label key that the selector applies to.
						"key"!: string
						// operator represents a key's relationship to a set of values.
						// Valid operators are In, NotIn, Exists and DoesNotExist.
						"operator"!: string
						// values is an array of string values. If the operator is In or NotIn,
						// the values array must be non-empty. If the operator is Exists or DoesNotExist,
						// the values array must be empty. This array is replaced during a strategic
						// merge patch.
						"values"?: [...string]
					}]
					// matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels
					// map is equivalent to an element of matchExpressions, whose key field is "key", the
					// operator is "In", and the values array contains only "value". The requirements are ANDed.
					"matchLabels"?: {[string]: string}
				}
				// Namespaces are the namespaces this entry applies to, as names or globs
				// ("tenant-*", matched with path.Match). Leave both matchers unset to make the
				// entry the default.
				"namespaces"?: [...string]
				// Warn is the count at or above which the Application is admitted with a
				// warning.
				"warn"?: int
			}]
		}
		// Version is the semantic version of this definition. Setting it makes each
		// version a distinct DefinitionRevision, so a binding can pin one with
		// `type: my-source@v1` and stop tracking whatever is newest.
		"version"?: string
	}
	"trait": {
		// Abstract marks this definition as one that may only be extended, never
		// named directly by an Application. A base that applies a platform's rules
		// is not something to use as-is, and saying so here is what makes the
		// definitions built on it the only way through.
		// It is not inherited: a definition that extends an abstract one is usable
		// unless it marks itself abstract too.
		"abstract"?: bool
		// AppliesToWorkloads specifies the list of workload kinds this trait
		// applies to. Workload kinds are specified in resource.group/version format,
		// e.g. server.core.oam.dev/v1alpha2. Traits that omit this field apply to
		// all workload kinds.
		"appliesToWorkloads"?: [...string]
		// ConflictsWith specifies the list of traits(CRD name, Definition name, CRD group)
		// which could not apply to the same workloads with this trait.
		// Traits that omit this field can work with any other traits.
		// Example rules:
		// "service" # Trait definition name
		// "services.k8s.io" # API resource/crd name
		// "*.networking.k8s.io" # API group
		// "labelSelector:foo=bar" # label selector
		// labelSelector format: https://pkg.go.dev/k8s.io/apimachinery/pkg/labels#Parse
		"conflictsWith"?: [...string]
		// ControlPlaneOnly defines which cluster is dispatched to
		"controlPlaneOnly"?: bool
		// Reference to the CustomResourceDefinition that defines this trait kind.
		"definitionRef"?: {
			// Name of the referenced CustomResourceDefinition.
			"name"!: string
			// Version indicate which version should be used if CRD has multiple versions
			// by default it will use the first one if not specified
			"version"?: string
		}
		// Extends names a TraitDefinition this one builds on. The parent renders
		// with the parameters this definition's template passes it in its `$super`
		// block, and its patch, patchOutputs, outputs and parameter schema are
		// inherited unless the template says otherwise with `$inherit`.
		// A DefinitionRevision may be named to pin the parent, as in "gateway@v2";
		// an unqualified name tracks whatever is current. The ancestors a render
		// resolved are recorded in the ApplicationRevision, so an application keeps
		// rendering the same way after a parent changes.
		"extends"?: string
		// Extension is used for extension needs by OAM platform builders
		"extension"?: {...}
		// ManageWorkload defines the trait would be responsible for creating the workload
		"manageWorkload"?: bool
		// PodDisruptive indicates that this trait is disruptive to the pod: applying or
		// updating it should cause the workload's pods to restart. If the trait's CUE
		// template patches the workload's pod template directly (`patch:` on
		// `spec.template`), the restart happens automatically via the normal Kubernetes
		// rollout mechanism and this field is not required.
		// If the trait instead renders separate objects via `outputs:` (e.g. a ConfigMap
		// consumed by the workload), set this to true so KubeVela stamps a content hash of
		// the trait's rendered output onto the workload's pod template annotations
		// (`app.oam.dev/trait-restart-hash-<traitType>`). This causes the pod template to
		// change whenever the trait's applied configuration changes, which in turn causes
		// the owning controller (Deployment/StatefulSet/CloneSet/...) to roll the pods.
		// Workloads without a `spec.template` (e.g. a bare Service) are unaffected.
		"podDisruptive"?: bool
		// Restrictions limits where this definition may be used. Absent or empty means
		// usable anywhere. A non-empty block overrides the
		// definition.oam.dev/restrict-namespaces annotation.
		"restrictions"?: {
			// NamespaceSelector selects those namespaces by label instead, for membership
			// that is not a naming convention. An empty selector matches every namespace;
			// leave the field unset to express no opinion.
			// Anyone who can label a namespace can bring it into scope, which a name glob
			// does not allow without the right to create namespaces.
			"namespaceSelector"?: {
				// matchExpressions is a list of label selector requirements. The requirements are ANDed.
				"matchExpressions"?: [...{
					// key is the label key that the selector applies to.
					"key"!: string
					// operator represents a key's relationship to a set of values.
					// Valid operators are In, NotIn, Exists and DoesNotExist.
					"operator"!: string
					// values is an array of string values. If the operator is In or NotIn,
					// the values array must be non-empty. If the operator is Exists or DoesNotExist,
					// the values array must be empty. This array is replaced during a strategic
					// merge patch.
					"values"?: [...string]
				}]
				// matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels
				// map is equivalent to an element of matchExpressions, whose key field is "key", the
				// operator is "In", and the values array contains only "value". The requirements are ANDed.
				"matchLabels"?: {[string]: string}
			}
			// Namespaces are the namespaces whose Applications may use this definition, as
			// names or globs ("tenant-*", matched with path.Match).
			"namespaces"?: [...string]
			// Quota limits how many uses of this definition one namespace may contain. The
			// first entry matching the namespace applies, so an entry with no matcher reads
			// as the default and belongs last. Absent or empty means unlimited.
			// Only ComponentDefinition and TraitDefinition are counted, and a quota on any
			// other kind is rejected when the definition is written. A namespace
			// accumulates components and the traits on them; a policy, workflow step or
			// source is part of how one Application is assembled.
			// The system namespace is never subject to a quota: addons install their own
			// Applications there using these definitions.
			"quota"?: [...{
				// Limit is the most uses of this definition the namespace may contain. Omit to
				// warn without ever refusing; zero forbids the type outright.
				"limit"?: int
				// NamespaceSelector selects those namespaces by label instead. It and
				// Namespaces are alternatives, so either one matching selects the entry.
				"namespaceSelector"?: {
					// matchExpressions is a list of label selector requirements. The requirements are ANDed.
					"matchExpressions"?: [...{
						// key is the label key that the selector applies to.
						"key"!: string
						// operator represents a key's relationship to a set of values.
						// Valid operators are In, NotIn, Exists and DoesNotExist.
						"operator"!: string
						// values is an array of string values. If the operator is In or NotIn,
						// the values array must be non-empty. If the operator is Exists or DoesNotExist,
						// the values array must be empty. This array is replaced during a strategic
						// merge patch.
						"values"?: [...string]
					}]
					// matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels
					// map is equivalent to an element of matchExpressions, whose key field is "key", the
					// operator is "In", and the values array contains only "value". The requirements are ANDed.
					"matchLabels"?: {[string]: string}
				}
				// Namespaces are the namespaces this entry applies to, as names or globs
				// ("tenant-*", matched with path.Match). Leave both matchers unset to make the
				// entry the default.
				"namespaces"?: [...string]
				// Warn is the count at or above which the Application is admitted with a
				// warning.
				"warn"?: int
			}]
		}
		// Revision indicates whether a trait is aware of component revision
		"revisionEnabled"?: bool
		// Stage defines the stage information to which this trait resource processing belongs.
		// Currently, PreDispatch and PostDispatch are provided, which are used to control resource
		// pre-process and post-process respectively.
		"stage"?: string
		// Status defines the custom health policy and status message for trait
		"status"?: {
			// CustomStatus defines the custom status message that could display to user
			"customStatus"?: string
			// Details stores a string representation of a CUE status map to be evaluated at runtime for display
			"details"?: string
			// HealthPolicy defines the health check policy for the abstraction
			"healthPolicy"?: string
		}
		"version"?: string
		// WorkloadRefPath indicates where/if a trait accepts a workloadRef object
		"workloadRefPath"?: string
	}
	"workflow-step": {
		// Reference to the CustomResourceDefinition that defines this trait kind.
		"definitionRef"?: {
			// Name of the referenced CustomResourceDefinition.
			"name"!: string
			// Version indicate which version should be used if CRD has multiple versions
			// by default it will use the first one if not specified
			"version"?: string
		}
		// Restrictions limits where this definition may be used. Absent or empty means
		// usable anywhere. A non-empty block overrides the
		// definition.oam.dev/restrict-namespaces annotation.
		"restrictions"?: {
			// NamespaceSelector selects those namespaces by label instead, for membership
			// that is not a naming convention. An empty selector matches every namespace;
			// leave the field unset to express no opinion.
			// Anyone who can label a namespace can bring it into scope, which a name glob
			// does not allow without the right to create namespaces.
			"namespaceSelector"?: {
				// matchExpressions is a list of label selector requirements. The requirements are ANDed.
				"matchExpressions"?: [...{
					// key is the label key that the selector applies to.
					"key"!: string
					// operator represents a key's relationship to a set of values.
					// Valid operators are In, NotIn, Exists and DoesNotExist.
					"operator"!: string
					// values is an array of string values. If the operator is In or NotIn,
					// the values array must be non-empty. If the operator is Exists or DoesNotExist,
					// the values array must be empty. This array is replaced during a strategic
					// merge patch.
					"values"?: [...string]
				}]
				// matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels
				// map is equivalent to an element of matchExpressions, whose key field is "key", the
				// operator is "In", and the values array contains only "value". The requirements are ANDed.
				"matchLabels"?: {[string]: string}
			}
			// Namespaces are the namespaces whose Applications may use this definition, as
			// names or globs ("tenant-*", matched with path.Match).
			"namespaces"?: [...string]
			// Quota limits how many uses of this definition one namespace may contain. The
			// first entry matching the namespace applies, so an entry with no matcher reads
			// as the default and belongs last. Absent or empty means unlimited.
			// Only ComponentDefinition and TraitDefinition are counted, and a quota on any
			// other kind is rejected when the definition is written. A namespace
			// accumulates components and the traits on them; a policy, workflow step or
			// source is part of how one Application is assembled.
			// The system namespace is never subject to a quota: addons install their own
			// Applications there using these definitions.
			"quota"?: [...{
				// Limit is the most uses of this definition the namespace may contain. Omit to
				// warn without ever refusing; zero forbids the type outright.
				"limit"?: int
				// NamespaceSelector selects those namespaces by label instead. It and
				// Namespaces are alternatives, so either one matching selects the entry.
				"namespaceSelector"?: {
					// matchExpressions is a list of label selector requirements. The requirements are ANDed.
					"matchExpressions"?: [...{
						// key is the label key that the selector applies to.
						"key"!: string
						// operator represents a key's relationship to a set of values.
						// Valid operators are In, NotIn, Exists and DoesNotExist.
						"operator"!: string
						// values is an array of string values. If the operator is In or NotIn,
						// the values array must be non-empty. If the operator is Exists or DoesNotExist,
						// the values array must be empty. This array is replaced during a strategic
						// merge patch.
						"values"?: [...string]
					}]
					// matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels
					// map is equivalent to an element of matchExpressions, whose key field is "key", the
					// operator is "In", and the values array contains only "value". The requirements are ANDed.
					"matchLabels"?: {[string]: string}
				}
				// Namespaces are the namespaces this entry applies to, as names or globs
				// ("tenant-*", matched with path.Match). Leave both matchers unset to make the
				// entry the default.
				"namespaces"?: [...string]
				// Warn is the count at or above which the Application is admitted with a
				// warning.
				"warn"?: int
			}]
		}
		"version"?: string
	}
	"workload": {
		// ChildResourceKinds are the list of GVK of the child resources this workload generates
		"childResourceKinds"?: [...{
			// APIVersion of the child resource
			"apiVersion"!: string
			// Kind of the child resource
			"kind"!: string
			// Selector to select the child resources that the workload wants to expose to traits
			"selector"?: {[string]: string}
		}]
		// Reference to the CustomResourceDefinition that defines this workload kind.
		"definitionRef"!: {
			// Name of the referenced CustomResourceDefinition.
			"name"!: string
			// Version indicate which version should be used if CRD has multiple versions by default it will use the first one if not specified
			"version"?: string
		}
		// Extension is used for extension needs by OAM platform builders
		"extension"?: {...}
		// PodSpecPath indicates where/if this workload has K8s podSpec field if one workload has podSpec, trait can do lot's of assumption such as port, env, volume fields.
		"podSpecPath"?: string
		// RevisionLabel indicates which label for underlying resources(e.g. pods) of this workload can be used by trait to create resource selectors(e.g. label selector for pods).
		"revisionLabel"?: string
		// Status defines the custom health policy and status message for workload
		"status"?: {
			// CustomStatus defines the custom status message that could display to user
			"customStatus"?: string
			// HealthPolicy defines the health check policy for the abstraction
			"healthPolicy"?: string
		}
	}
}
