/*
Copyright 2026 The KubeVela Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package analysis

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"testing"

	"cuelang.org/go/cue/format"
	"github.com/stretchr/testify/require"
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	"sigs.k8s.io/yaml"
)

var update = flag.Bool("update", false, "regenerate header_attributes.cue from the Definition CRDs")

// crdOf is the Definition CRD each definition type's attributes come from.
var crdOf = map[string]string{
	componentType:    "core.oam.dev_componentdefinitions.yaml",
	traitType:        "core.oam.dev_traitdefinitions.yaml",
	policyType:       "core.oam.dev_policydefinitions.yaml",
	workflowStepType: "core.oam.dev_workflowstepdefinitions.yaml",
	sourceType:       "core.oam.dev_sourcedefinitions.yaml",
	workloadType:     "core.oam.dev_workloaddefinitions.yaml",
}

// header_attributes.cue is generated from the CRDs, so a field added to a
// Definition's spec is accepted in the header as soon as the CRDs are. Run
// `go test ./pkg/definition/analysis -run TestHeaderAttributesMatchTheCRDs -update`
// after changing them.
func TestHeaderAttributesMatchTheCRDs(t *testing.T) {
	got, err := generateHeaderAttributes(filepath.Join("..", "..", "..", "charts", "vela-core", "crds"))
	require.NoError(t, err)
	if *update {
		require.NoError(t, os.WriteFile("header_attributes.cue", got, 0o600))
	}
	want, err := os.ReadFile("header_attributes.cue")
	require.NoError(t, err)
	require.Equal(t, string(got), string(want), "header_attributes.cue is stale: rerun this test with -update")
}

func generateHeaderAttributes(crdDir string) ([]byte, error) {
	types := make([]string, 0, len(crdOf))
	for t := range crdOf {
		types = append(types, t)
	}
	sort.Strings(types)
	var b strings.Builder
	b.WriteString("// Code generated by TestHeaderAttributesMatchTheCRDs from charts/vela-core/crds. DO NOT EDIT.\n\n")
	b.WriteString("// #attributes is what a definition header's attributes may hold, by type:\n")
	b.WriteString("// the Definition CRD's spec, less the schematic, which is the template.\n")
	b.WriteString("#attributes: {\n")
	for _, typ := range types {
		data, err := os.ReadFile(filepath.Join(crdDir, crdOf[typ]))
		if err != nil {
			return nil, err
		}
		var crd apiextensionsv1.CustomResourceDefinition
		if err := yaml.Unmarshal(data, &crd); err != nil {
			return nil, fmt.Errorf("%s: %w", crdOf[typ], err)
		}
		var spec *apiextensionsv1.JSONSchemaProps
		for _, v := range crd.Spec.Versions {
			if v.Storage {
				s := v.Schema.OpenAPIV3Schema.Properties["spec"]
				spec = &s
			}
		}
		if spec == nil {
			return nil, fmt.Errorf("%s has no storage version with a spec", crdOf[typ])
		}
		delete(spec.Properties, "schematic")
		fmt.Fprintf(&b, "%s: %s\n", strconv.Quote(typ), cueType(*spec))
	}
	b.WriteString("}\n")
	return format.Source([]byte(b.String()))
}

// cueType is the CUE for an OpenAPI schema. Structs are closed by #attributes
// being a definition, unless the schema keeps unknown fields.
func cueType(s apiextensionsv1.JSONSchemaProps) string {
	var t string
	switch {
	case s.XIntOrString:
		t = "int | string"
	case len(s.Enum) > 0:
		alts := make([]string, 0, len(s.Enum))
		for _, e := range s.Enum {
			alts = append(alts, string(e.Raw))
		}
		t = strings.Join(alts, " | ")
	case s.Type == "object" && len(s.Properties) > 0:
		t = cueStruct(s)
	case s.Type == "object" && s.AdditionalProperties != nil && s.AdditionalProperties.Schema != nil:
		t = "{[string]: " + cueType(*s.AdditionalProperties.Schema) + "}"
	case s.Type == "object":
		t = "{...}"
	case s.Type == "array" && s.Items != nil && s.Items.Schema != nil:
		t = "[..." + cueType(*s.Items.Schema) + "]"
	case s.Type == "array":
		t = "[...]"
	case s.Type == "string":
		t = "string"
	case s.Type == "boolean":
		t = "bool"
	case s.Type == "integer":
		t = "int"
	case s.Type == "number":
		t = "number"
	default:
		t = "_"
	}
	if s.Nullable {
		t += " | null"
	}
	return t
}

func cueStruct(s apiextensionsv1.JSONSchemaProps) string {
	names := make([]string, 0, len(s.Properties))
	for n := range s.Properties {
		names = append(names, n)
	}
	sort.Strings(names)
	var b strings.Builder
	b.WriteString("{\n")
	for _, n := range names {
		p := s.Properties[n]
		for _, line := range strings.Split(strings.TrimSpace(p.Description), "\n") {
			if line != "" {
				fmt.Fprintf(&b, "// %s\n", line)
			}
		}
		// Every field is optional: the header is decoded into the Definition's Go
		// type before it is applied, which writes a non-pointer struct's fields
		// whether the header has them or not, so a CRD's required field is never
		// missing by then.
		fmt.Fprintf(&b, "%s?: %s\n", strconv.Quote(n), cueType(p))
	}
	if s.XPreserveUnknownFields != nil && *s.XPreserveUnknownFields {
		b.WriteString("...\n")
	}
	b.WriteString("}")
	return b.String()
}
