/*
Copyright 2023 The KubeVela Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by TestFeatureGateDocs -update-feature-gates. DO NOT EDIT.

package lsp

// featureGateDocs are the gates a KubeVela controller is built with, from their source files.
var featureGateDocs = []FeatureGateInfo{
	{Name: "ApplyOnce", Source: "kubevela", Description: "Enable the apply-once feature for all applications If enabled, no StateKeep will be run, ResourceTracker will also disable the storage of all resource data, only metadata will be kept"},
	{Name: "ApplyResourceByReplace", Source: "kubevela", Description: "Enforces the modification of resource through PUT requests. If not set, the resource modification will use patch requests (three-way-strategy-merge-patch). The side effect of enabling this feature is that the request traffic will increase due to the increase of bytes transferred and the more frequent resource mutation failure due to the potential conflicts. If set, KubeVela controller will enforce strong restriction on the managed resource that external system would be unable to make modifications to the KubeVela managed resource. In other words, no merge for modifications from multiple sources. Only KubeVela keeps the Source-of-Truth for the resource."},
	{Name: "AuthenticateApplication", Source: "kubevela", Description: "Enable the authentication for application"},
	{Name: "BlockPrivateHTTPAddresses", Source: "workflow", Description: "If set, outbound HTTP to RFC-1918 and ULA destinations is blocked"},
	{Name: "ClientIdentityPenetration", Source: "multicluster", Description: "Enforce impersonate as the original request user when accessing apiserver in ManagedCluster"},
	{Name: "DeprecatedObjectLabelSelector", Source: "kubevela", Description: "Enable the use of deprecated object label selector for selecting ref-object"},
	{Name: "DeprecatedPolicySpec", Source: "kubevela", Description: "Enable the use of deprecated policy spec"},
	{Name: "DisableBootstrapClusterInfo", Source: "kubevela", Description: "Disable the cluster info bootstrap at the starting of the controller"},
	{Name: "DisableReferObjectsFromURL", Source: "kubevela", Description: "If set, the url ref objects will be disallowed"},
	{Name: "DisableWebhookAutoSchedule", Source: "kubevela", Description: "Disable auto schedule for application mutating webhook when sharding enabled If set to true, the webhook will not make auto schedule for applications and users can make customized scheduler for assigning shards to applications"},
	{Name: "DisableWorkflowContextConfigMapCache", Source: "kubevela", Description: "Disable the workflow context's configmap informer cache"},
	{Name: "DisableWorkflowHTTP", Source: "workflow", Description: "If set, outbound HTTP from workflow request/webhook steps is disallowed"},
	{Name: "EnableAddonComponent", Source: "kubevela", Description: "Enables installing an addon as an Application component via the type: addon ComponentDefinition. The ComponentDefinition and its vela/addon CueX package always ship, because the definition cannot compile without the package; this gate controls whether the render service is wired up and whether the shared Application webhook runs its addon-specific compatibility-validation branch. The shared Application webhook is always registered. When disabled, nothing addon-specific runs and an Application using type: addon fails at render with an actionable message."},
	{Name: "EnableApplicationScopedPolicies", Source: "kubevela", Description: "Enables the execution of Application-scoped policies. When disabled, policies with scope: Application will not be applied (both global and explicit). This gates the core Application transform functionality. Use EnableGlobalPolicies to separately control global policy discovery."},
	{Name: "EnableApplicationStatusMetrics", Source: "kubevela", Description: "Enable the collection and export of application status metrics and structured logging"},
	{Name: "EnableBackupWorkflowRecord", Source: "workflow", Description: "Enable backup workflow record"},
	{Name: "EnableCelExpressions", Source: "kubevela", Description: "Turns on $( ) property expressions, and with them SourceDefinition, which cannot be used without them. The dependency runs one way: an expression reading $(context.namespace) needs no source at all, so this gate is named for the mechanism rather than for its first consumer."},
	{Name: "EnableCueValidation", Source: "kubevela", Description: "Enable strict cue validation fields for the required parameter field verification"},
	{Name: "EnableDefinitionInheritance", Source: "kubevela", Description: "Enables spec.extends on ComponentDefinition and TraitDefinition, letting a definition render on top of another. With the gate off a definition that sets the field is refused rather than ignored, since ignoring it would render the child's template with an unresolved `$super`."},
	{Name: "EnableGlobalPolicies", Source: "kubevela", Description: "Enables automatic discovery of global PolicyDefinitions Controls whether policies with global: true are discovered from vela-system and namespace"},
	{Name: "EnablePatchStatusAtOnce", Source: "workflow", Description: "Enable patch status at once"},
	{Name: "EnableSourceAutoUpdate", Source: "kubevela", Description: "Is the controller-wide default for source-driven re-dispatch: whether a component is re-applied when a value it read from a SourceDefinition changes. It decides only what happens to an Application carrying no opinion of its own - spec.sources[].autoUpdate overrides it in both directions, and a publishVersion pin suppresses the refresh regardless."},
	{Name: "EnableSuspendOnFailure", Source: "workflow", Description: "Enable suspend on workflow failure"},
	{Name: "EnableWatchEventListener", Source: "workflow", Description: "Enable watch event listener"},
	{Name: "GzipApplicationRevision", Source: "kubevela", Description: "Serves the same purpose as GzipResourceTracker, but for ApplicationRevision."},
	{Name: "GzipResourceTracker", Source: "kubevela", Description: "Enables the gzip compression for ResourceTracker. It can be useful if you have large application that needs to dispatch lots of resources or large resources (like CRD or huge ConfigMap), which at the cost of slower processing speed due to the extra overhead for compression and decompression."},
	{Name: "HealthinessCheck", Source: "multicluster", Description: "Enables the \"/health\" subresource on the ClusterGateway by which we can read/update the healthiness related status under the \".status\"."},
	{Name: "InformerCacheFilterUnnecessaryFields", Source: "kubevela", Description: "Filter unnecessary fields for informer cache"},
	{Name: "LegacyObjectTypeIdentifier", Source: "kubevela", Description: "Enable the use of legacy object type identifier for selecting ref-object"},
	{Name: "LegacyResourceOwnerValidation", Source: "kubevela", Description: "If enabled, the resource dispatch will allow existing resource not to have owner application and the current application will take over it"},
	{Name: "LegacyResourceTrackerGC", Source: "kubevela", Description: "Enable the gc of legacy resource tracker in managed clusters"},
	{Name: "MultiStageComponentApply", Source: "kubevela", Description: "Enable multi-stage feature for component If enabled, the dispatch of manifests is performed in batches according to the stage"},
	{Name: "OCMClusterCache", Source: "multicluster", Description: "SecretCache runs a OCM ManagedCluster informer inside the apiserver which provides a cache for reading ManagedCluster."},
	{Name: "PreDispatchDryRun", Source: "kubevela", Description: "Enable dryrun before dispatching resources Enable this flag can help prevent unsuccessful dispatch resources entering resourcetracker and improve the user experiences of gc but at the cost of increasing network requests."},
	{Name: "RequireCelExpressionOptIn", Source: "kubevela", Description: "Keeps expressions to Applications that ask for them by annotation, so enabling the feature is not itself a fleet-wide change."},
	{Name: "RestrictDefinitionNamespaces", Source: "kubevela", Description: "Enforces a definition's spec.restrictions, or its definition.oam.dev/restrict-namespaces annotation, when an Application is written. Defaults on: it does nothing until a definition declares a restriction, and is here to switch enforcement off, not on."},
	{Name: "SecretCache", Source: "multicluster", Description: "Runs a namespaced secret informer inside the apiserver which provides a cache for reading secret data."},
	{Name: "SharedDefinitionStorageForApplicationRevision", Source: "kubevela", Description: "Use definition cache to reduce duplicated definition storage for application revision, must be used with InformerCacheFilterUnnecessaryFields"},
	{Name: "ValidateComponentWhenSharding", Source: "kubevela", Description: "Validate component in sharding mode In sharding mode, since ApplicationRevision will not be cached for webhook, the validation of component need to call Kubernetes APIServer which can be slow and take up some network traffic. So by default, the validation of component will be disabled."},
	{Name: "ValidateDefinitionPermissions", Source: "kubevela", Description: "Enables RBAC validation for definition access in applications"},
	{Name: "ValidateResourcesExist", Source: "kubevela", Description: "Enables webhook validation to check if resource types referenced in ComponentDefinition/TraitDefinition/WorkflowStepDefinition/PolicyDefinition CUE templates exist in the cluster"},
	{Name: "ValidateUndeclaredParameters", Source: "kubevela", Description: "Enables validation that rejects parameters not declared in the CUE definition schema. When enabled, any parameter field not present in the template's parameter stanza will cause a validation error at admission time."},
	{Name: "ZstdApplicationRevision", Source: "kubevela", Description: "Serves the same purpose as ZstdResourceTracker, but for ApplicationRevision."},
	{Name: "ZstdResourceTracker", Source: "kubevela", Description: "Enables the zstd compression for ResourceTracker. Refer to GzipResourceTracker for its use-cases. It is much faster and more efficient than gzip, about 2x faster and compresses to smaller size. If you are dealing with very large ResourceTrackers (1MB or so), it should have almost NO performance penalties compared to no compression at all. If dealing with smaller ResourceTrackers (10KB - 1MB), the performance penalties are minimal."},
}
