/*
Copyright 2026 The KubeVela Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package lsp

import (
	"bytes"
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"sigs.k8s.io/controller-runtime/pkg/client/fake"

	"github.com/oam-dev/kubevela/pkg/definition/analysis"
	"github.com/oam-dev/kubevela/pkg/utils/common"
)

var updateFeatureGates = flag.Bool("update-feature-gates", false, "rewrite featuregates_generated.go from the gates' source files")

const featureGatesFile = "featuregates_generated.go"

// featureGateSources are the files declaring the gates a KubeVela controller
// is built with, by the module each is in.
var featureGateSources = []struct{ source, module, file string }{
	{source: "kubevela", file: filepath.Join("..", "..", "features", "controller_features.go")},
	{source: "workflow", module: "github.com/kubevela/workflow", file: "pkg/features/controller_features.go"},
	{source: "multicluster", module: "github.com/oam-dev/cluster-gateway", file: "pkg/featuregates/featue_gate.go"},
}

// The table of gates is what their source files declare. Run
// go test ./pkg/definition/lsp -run TestFeatureGateDocs -update-feature-gates
// after a dependency bump.
func TestFeatureGateDocs(t *testing.T) {
	var gates []FeatureGateInfo
	for _, s := range featureGateSources {
		path := s.file
		if s.module != "" {
			out, err := exec.Command("go", "list", "-m", "-f", "{{.Dir}}", s.module).Output()
			require.NoError(t, err, s.module)
			path = filepath.Join(strings.TrimSpace(string(out)), s.file)
		}
		gates = append(gates, parseFeatureGates(t, path, s.source)...)
	}
	sort.Slice(gates, func(i, j int) bool { return gates[i].Name < gates[j].Name })
	if *updateFeatureGates {
		require.NoError(t, os.WriteFile(featureGatesFile, generatedFeatureGates(gates), 0o600))
		return
	}
	assert.Equal(t, gates, featureGateDocs, "run this test with -update-feature-gates")
}

// parseFeatureGates are the keys of the FeatureSpec maps a file declares,
// each described by the paragraph of its constant's comment that names it.
func parseFeatureGates(t *testing.T, path, source string) []FeatureGateInfo {
	t.Helper()
	f, err := parser.ParseFile(token.NewFileSet(), path, nil, parser.ParseComments)
	require.NoError(t, err)
	docs := map[string]string{}
	for _, d := range f.Decls {
		if g, ok := d.(*ast.GenDecl); ok && g.Tok == token.CONST {
			for _, spec := range g.Specs {
				v := spec.(*ast.ValueSpec)
				docs[v.Names[0].Name] = v.Doc.Text()
			}
		}
	}
	var out []FeatureGateInfo
	ast.Inspect(f, func(n ast.Node) bool {
		lit, ok := n.(*ast.CompositeLit)
		if !ok {
			return true
		}
		if m, ok := lit.Type.(*ast.MapType); !ok || !isSelector(m.Value, "FeatureSpec") {
			return true
		}
		for _, e := range lit.Elts {
			if key, ok := e.(*ast.KeyValueExpr).Key.(*ast.Ident); ok {
				out = append(out, FeatureGateInfo{Name: key.Name, Source: source, Description: describeGate(key.Name, docs[key.Name])})
			}
		}
		return false
	})
	require.NotEmpty(t, out, path)
	return out
}

func isSelector(e ast.Expr, name string) bool {
	sel, ok := e.(*ast.SelectorExpr)
	return ok && sel.Sel.Name == name
}

// describeGate is the paragraph of a doc comment that starts with the
// gate's name, else its first, the name dropped and the first letter raised.
func describeGate(name, doc string) string {
	var paragraphs []string
	for _, p := range strings.Split(doc, "\n\n") {
		if p = strings.Join(strings.Fields(p), " "); p != "" && !strings.HasPrefix(p, "owner:") {
			paragraphs = append(paragraphs, p)
		}
	}
	if len(paragraphs) == 0 {
		return ""
	}
	text := paragraphs[0]
	for _, p := range paragraphs {
		if strings.HasPrefix(p, name+" ") {
			text = p
			break
		}
	}
	text = strings.TrimPrefix(text, name+" ")
	return strings.ToUpper(text[:1]) + text[1:]
}

func generatedFeatureGates(gates []FeatureGateInfo) []byte {
	var b bytes.Buffer
	header, err := os.ReadFile(filepath.Join("..", "..", "..", "hack", "boilerplate.go.txt"))
	if err == nil {
		b.Write(header)
		b.WriteString("\n")
	}
	b.WriteString("// Code generated by TestFeatureGateDocs -update-feature-gates. DO NOT EDIT.\n\npackage lsp\n\n")
	b.WriteString("// featureGateDocs are the gates a KubeVela controller is built with, from their source files.\nvar featureGateDocs = []FeatureGateInfo{\n")
	for _, g := range gates {
		fmt.Fprintf(&b, "\t{Name: %q, Source: %q, Description: %q},\n", g.Name, g.Source, g.Description)
	}
	b.WriteString("}\n")
	return b.Bytes()
}

func TestDescribeGate(t *testing.T) {
	assert.Equal(t, "Enables the health subresource.", describeGate("HealthinessCheck", "owner: @x\nalpha: v1.1\n\nHealthinessCheck enables the\nhealth subresource.\n\nAdditionally, more."))
	assert.Equal(t, "Enable suspend on failure", describeGate("EnableSuspendOnFailure", "EnableSuspendOnFailure enable suspend on failure\n"))
	assert.Equal(t, "", describeGate("X", ""))
}

// The client is served every gate with where it is from and what it does.
func TestFeatureGatesRequest(t *testing.T) {
	c := newClient(t)
	var got FeatureGatesResult
	require.NoError(t, json.Unmarshal(c.response(c.send(MethodFeatureGates, struct{}{}, true))["result"], &got))
	by := map[string]FeatureGateInfo{}
	for _, g := range got.Gates {
		by[g.Name] = g
	}
	assert.Equal(t, "kubevela", by["EnableCelExpressions"].Source)
	assert.Equal(t, "workflow", by["EnableSuspendOnFailure"].Source)
	assert.Equal(t, "multicluster", by["SecretCache"].Source)
	assert.NotEmpty(t, by["ApplyResourceByReplace"].Description)
}

// The controller is read from its Deployment: its image and the gates its
// args set.
func TestReadController(t *testing.T) {
	replicas := int32(1)
	deploy := &appsv1.Deployment{
		ObjectMeta: metav1.ObjectMeta{Name: "kubevela-vela-core", Namespace: "vela-system", Labels: map[string]string{"controller.oam.dev/name": "vela-core"}},
		Spec: appsv1.DeploymentSpec{Replicas: &replicas, Template: corev1.PodTemplateSpec{Spec: corev1.PodSpec{Containers: []corev1.Container{{
			Name:  "kubevela",
			Image: "oamdev/vela-core:v1.11.0",
			Args:  []string{"--webhook-port=9443", "--feature-gates=EnableGlobalPolicies=false", "--feature-gates=A=true,B=false", "--feature-gates=MultiStageComponentApply= true"},
		}}}}},
	}
	cli := fake.NewClientBuilder().WithScheme(common.Scheme).WithObjects(deploy).Build()
	got, err := readController(context.Background(), cli)
	require.NoError(t, err)
	assert.Equal(t, &ControllerInfo{Image: "oamdev/vela-core:v1.11.0", Version: "v1.11.0", Replicas: 1, Set: map[string]bool{"EnableGlobalPolicies": false, "A": true, "B": false, "MultiStageComponentApply": true}}, got)

	none, err := readController(context.Background(), fake.NewClientBuilder().WithScheme(common.Scheme).Build())
	require.NoError(t, err)
	assert.Nil(t, none)
}

// The gates checked against are the args' values, else the defaults the
// controller's --help gave, once the client has sent them; a gate --help
// does not list is one the controller lacks.
func TestControllerGates(t *testing.T) {
	ctl := &ControllerInfo{Image: "oamdev/vela-core:v1.11.0", Version: "v1.11.0", Replicas: 1, Set: map[string]bool{"EnableGlobalPolicies": false}}
	g := controllerGates("k3d-vela", ctl, nil)
	assert.Equal(t, &analysis.ControllerGates{Context: "k3d-vela", Version: "v1.11.0", On: map[string]bool{"EnableGlobalPolicies": false}, Missing: map[string]bool{}}, g)

	help := map[string]bool{"EnableGlobalPolicies": false, "EnableApplicationScopedPolicies": false, "MultiStageComponentApply": true}
	g = controllerGates("k3d-vela", ctl, help)
	assert.Equal(t, false, g.On["EnableApplicationScopedPolicies"], "its default")
	assert.True(t, g.Missing["EnableCelExpressions"], "a KubeVela gate --help does not list")
	assert.False(t, g.Missing["SomeLibraryGate"], "only the gates this server knows are judged missing")

	assert.Nil(t, controllerGates("k3d-vela", &ControllerInfo{Replicas: 0, Set: map[string]bool{}}, nil), "a controller scaled to 0 runs elsewhere, with other args")
	assert.Nil(t, controllerGates("k3d-vela", nil, nil))
}

// A fix that runs a command is offered as a code action with it.
func TestCommandFixAction(t *testing.T) {
	data := fixesData("", []analysis.Fix{{Title: "Turn on X", Command: &analysis.FixCommand{Name: "kubevela.controller.open", Arguments: []interface{}{map[string]interface{}{"gate": "X", "value": true}}}}})
	actions := upgradeActions(CodeActionParams{TextDocument: TextDocumentIdentifier{URI: "file:///a.cue"}, Context: CodeActionContext{Diagnostics: []Diagnostic{{Message: "X is off", Data: data}}}}, "")
	require.Len(t, actions, 1)
	assert.Equal(t, "Turn on X", actions[0].Title)
	assert.Equal(t, &Command{Title: "Turn on X", Command: "kubevela.controller.open", Arguments: []interface{}{map[string]interface{}{"gate": "X", "value": true}}}, actions[0].Command)
}

// A file using a feature the cluster's controller has off is warned of,
// with a fix that opens the controller's gates.
func TestGateDiagnostics(t *testing.T) {
	cluster := func() (Cluster, error) {
		c, err := velaCluster()
		c.Controller = &ControllerInfo{Image: "oamdev/vela-core:v1.12.0", Version: "v1.12.0", Replicas: 1, Set: map[string]bool{"EnableCelExpressions": false}}
		return c, err
	}
	app := "apiVersion: core.oam.dev/v1beta1\nkind: Application\nmetadata:\n  name: a\nspec:\n  components:\n    - name: web\n      type: webservice\n      properties:\n        image: $(context.namespace)\n"
	warned := func(ds []Diagnostic) bool {
		for _, d := range ds {
			if strings.Contains(d.Message, "EnableCelExpressions is off on k3d-test") {
				return true
			}
		}
		return false
	}
	_, _, diags := openWith(t, cluster, "auto", t.TempDir(), "app.yaml", app, warned)
	var found *Diagnostic
	for i := range diags {
		if strings.Contains(diags[i].Message, "EnableCelExpressions") {
			found = &diags[i]
		}
	}
	require.NotNil(t, found)
	assert.Equal(t, uint32(9), found.Range.Start.Line)
	assert.Contains(t, string(found.Data), `"command":"kubevela.controller.open"`)
}
